spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unsafe_drive?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: liu123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: localhost
    port: 6379
    password: root123456
    lettuce:
      pool:
        max-wait: 100 #连接等待时间
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-active: 10 #最大连接

server:
  port: 8816

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
